### ISSUE TITLE
Implement Scale Image Object

### ISSUE THREAD

**Issue by eigenholser** [eigenholser/flac2mp3#13]
Need an object that will take a source file, destination file, final resolution and will:

* Compute the scale factor (if necessary)
* Scale the source file to the final resolution in the destination file
* Write the file to the destination

Source format must be PNG or JPEG format. Destination file must be JPEG format. Please confirm on those requirements.

**Comment by eigenholser** [comment]
Purpose of scale image object is to produce JPEG cover and thumbnail files. The cover file will be embedded in the MP3 and probably the Flac at a later time in the process. The thumbnail may be used by streaming server. Ditto for the cover file.

This means we need an enum to indicate whether this is a COVER or THUMB scaling. In fact, we can derive the resolution from the enum - i.e. if COVER then read cover resolution from config, if THUMB then read thumb resolution from config. Ditto for cover and thumb filenames which should be "cover.jpg" and "thumb.jpg".

**Comment by reslohrevo** [comment]
#15
